# Generated by Django 5.2.1 on 2026-03-20 07:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0002_alter_occupieddate_room_alter_room_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='room',
            name='totalReviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
