# Generated by Django 5.2.1 on 2026-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0003_room_rating_room_totalreviews_alter_room_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.URLField(),
        ),
    ]
