# Generated by Django 5.2.1 on 2026-03-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomBooking', '0004_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='city',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='hasAC',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hasBreakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hasParking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hasPool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hasTV',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hasWifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('suite', 'Suite'), ('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium')], max_length=100),
        ),
    ]
